# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: codeline
# "service" is the name of this project. This will also be added to your AWS resource names.
service: JStack-food-diary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  architecture: arm64
  timeout: 10
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    BUCKET_NAME: !Ref UploadsBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          #Resource: !GetAtt UploadsBucket.Arn /*
          Resource: !Sub '${UploadsBucket.Arn}/*'

plugins:
  - serverless-offline

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: post
  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: post
  me:
    handler: src/functions/me.handler
    events:
      - httpApi:
          path: /me
          method: get
  createMeal:
    handler: src/functions/createMeal.handler
    events:
      - httpApi:
          path: /meals
          method: post
  listMeals:
    handler: src/functions/listMeals.handler
    events:
      - httpApi:
          path: /meals
          method: get
  getMealById:
    handler: src/functions/getMealById.handler
    events:
      - httpApi:
          path: /meals/{mealId}
          method: get

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: foodiary-for-uploads
